

const supabaseUrl = "https://ayvtsysvmkqeeexihvah.supabase.co"

const supabaseKey = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6ImF5dnRzeXN2bWtxZWVleGlodmFoIiwicm9sZSI6ImFub24iLCJpYXQiOjE2NzkyNzk2OTgsImV4cCI6MTk5NDg1NTY5OH0.1QdqopWNi8W6DwCVLpC5dprWmmrC7EUTxXo0LBRNOzM"

const _supabase = supabase.createClient(supabaseUrl, supabaseKey)